// Code generated by goctl. DO NOT EDIT.
package types

type Goods struct {
	Id          int64  `json:"id"`
	CategoryId  int64  `json:"categoryId"`
	Name        string `json:"name"`
	Ingredients string `json:"ingredients"`
	Tea         string `json:"tea"`
	CupCapacity string `json:"cup_capacity"`
	Reason      string `json:"reason"`
}

type DrinkGptReq struct {
	CategoryId int64    `json:"categoryId"`
	Phrases    []string `json:"prases"`
}

type DrinkGptResp struct {
	Drink Goods `json:"drink"`
}
