// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	category "github.com/ptonlix/drinkGPT/cmd/gpt/api/internal/handler/category"
	"github.com/ptonlix/drinkGPT/cmd/gpt/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/drinks/chat",
				Handler: category.ChatHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/gpt"),
	)
}
