// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	category "github.com/ptonlix/drinkGPT/cmd/drinks/api/internal/handler/category"
	goods "github.com/ptonlix/drinkGPT/cmd/drinks/api/internal/handler/goods"
	"github.com/ptonlix/drinkGPT/cmd/drinks/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/category/list",
				Handler: category.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/category/add",
				Handler: category.AddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/category/delete",
				Handler: category.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/category/update",
				Handler: category.UpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/drinks"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/goods/list",
				Handler: goods.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/goods/listbycategory",
				Handler: goods.ListbycategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/goods/add",
				Handler: goods.AddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/goods/delete",
				Handler: goods.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/goods/update",
				Handler: goods.UpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/drinks"),
	)
}
