// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/ptonlix/drinkGPT/common/globalkey"
	"github.com/ptonlix/drinkGPT/common/xerr"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	categoryFieldNames          = builder.RawFieldNames(&Category{})
	categoryRows                = strings.Join(categoryFieldNames, ",")
	categoryRowsExpectAutoSet   = strings.Join(stringx.Remove(categoryFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	categoryRowsWithPlaceHolder = strings.Join(stringx.Remove(categoryFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheDrinksgptCategoryIdPrefix = "cache:drinksgpt:category:id:"
)

type (
	categoryModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Category) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Category, error)
		Update(ctx context.Context, session sqlx.Session, data *Category) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Category) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultCategoryModel struct {
		sqlc.CachedConn
		table string
	}

	Category struct {
		Id         int64     `db:"id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`
		Version    int64     `db:"version"` // 版本号
		Name       string    `db:"name"`    // 饮品类型
		Desc       string    `db:"desc"`    // 类型说明
	}
)

func newCategoryModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultCategoryModel {
	return &defaultCategoryModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`category`",
	}
}

func (m *defaultCategoryModel) Insert(ctx context.Context, session sqlx.Session, data *Category) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	drinksgptCategoryIdKey := fmt.Sprintf("%s%v", cacheDrinksgptCategoryIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, categoryRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Desc)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Desc)
	}, drinksgptCategoryIdKey)
}

func (m *defaultCategoryModel) FindOne(ctx context.Context, id int64) (*Category, error) {
	drinksgptCategoryIdKey := fmt.Sprintf("%s%v", cacheDrinksgptCategoryIdPrefix, id)
	var resp Category
	err := m.QueryRowCtx(ctx, &resp, drinksgptCategoryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", categoryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCategoryModel) Update(ctx context.Context, session sqlx.Session, data *Category) (sql.Result, error) {
	drinksgptCategoryIdKey := fmt.Sprintf("%s%v", cacheDrinksgptCategoryIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, categoryRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Desc, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Desc, data.Id)
	}, drinksgptCategoryIdKey)
}

func (m *defaultCategoryModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Category) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	drinksgptCategoryIdKey := fmt.Sprintf("%s%v", cacheDrinksgptCategoryIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, categoryRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Desc, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Desc, data.Id, oldVersion)
	}, drinksgptCategoryIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return xerr.NewErrCode(xerr.DB_UPDATE_AFFECTED_ZERO_ERROR)
	}

	return nil
}

func (m *defaultCategoryModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	drinksgptCategoryIdKey := fmt.Sprintf("%s%v", cacheDrinksgptCategoryIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, drinksgptCategoryIdKey)
	return err
}

func (m *defaultCategoryModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheDrinksgptCategoryIdPrefix, primary)
}
func (m *defaultCategoryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", categoryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultCategoryModel) tableName() string {
	return m.table
}
